### ISSUE TITLE
When the code will be released?

### ISSUE THREAD

**Issue by LZL-CS** [ActiveVisionLab/NeFeS#1]
Hi @chenusc11, it's awesome work, may I know when you can release the code?

**Comment by chenusc11** [comment]
Hi. Thank you very much for your interest. I am working on it! We try to release it as quickly as we can.

**Comment by LZL-CS** [comment]
Hi @chenusc11, are you using 7Scenes dataset form this paper: https://github.com/tsattler/visloc_pseudo_gt_limitations?tab=readme-ov-file (dataset link: https://drive.google.com/file/d/1ATijcGCgK84NKB4Mho4_T-P7x8LSL80m/view?usp=sharing)?

**Comment by chenusc11** [comment]
Hi, that is correct.

**Comment by chenusc11** [comment]
Closing the issue for now. The code will be released ASAP.
