### ISSUE TITLE
config files for 7scenes_fire are not correct

### ISSUE THREAD

**Issue by Satuki717** [ActiveVisionLab/NeFeS#4]
Hi, thank you for your excellent work! 
When I tried to evaluate the performance of your pretrained models, I found that the files config_fire_DFM.txt, config_fire_stage1.txt, and config_fire_stage2.txt are identical to config_office_DFM.txt, config_office_stage1.txt, and config_office_stage2.txt.
It is easy to change the scene name, but I'm not sure if any settings are different.

**Comment by chenusc11** [comment]
Hi, Sorry for the mistake. Yes, I think you can simply replace the scene name. I will fix the typo.
